airbnb_snowflake_dbt:
  outputs:
    dev:
      account: pp34711.central-india.azure
      database: airbnb_elt
      password: Mynameismukul7890
      role: accountadmin
      schema: airbnb
      threads: 10
      type: snowflake
      user: mukulg
      warehouse: compute_wh
  target: dev
dbtsnow:
  outputs:
    dev:
      account: pp34711.central-india.azure
      database: airbnb_elt
      password: Mynameismukul7890
      role: accountadmin
      schema: airbnb
      user: mukulg
      warehouse: compute_wh
